version: '3.4'

services:
  nestjsdocker:
    image: nestjsdocker
    build:
      context: nestjs-docker
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: docker_nest
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: docker_nest
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
